"""empty message

Revision ID: 05348017ecd4
Revises: 
Create Date: 2024-07-24 14:54:33.970049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05348017ecd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('national_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('last_appointment', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('national_id')
    )
    op.create_table('medinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Medical_allergies', sa.String(), nullable=True),
    sa.Column('Medical_Conditions', sa.String(), nullable=True),
    sa.Column('Prescriptions', sa.String(), nullable=True),
    sa.Column('Surgeries_Procedures', sa.String(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('HospitalName', sa.String(), nullable=True),
    sa.Column('PatientName', sa.String(), nullable=True),
    sa.Column('DoctorName', sa.String(), nullable=True),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('MedicalReport', sa.LargeBinary(), nullable=True),
    sa.Column('PatientId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['PatientId'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medrecord')
    op.drop_table('medinfo')
    op.drop_table('patients')
    op.drop_table('doctors')
    # ### end Alembic commands ###
